# config.yml - Label Studio 配置文件模板
# 此文件中的配置项将覆盖同名环境变量（若存在）

dev:
  # 基础设置
  debug: true
  allowed_hosts:
    - "*"
  secret_key: "7#33_!ae+t7eg1n#5c0+xa811^a5d!+a0=b8a!*ha04m9wve_("

  # 主机与前端
  host: "http://localhost:8080"
  frontend_hostname: "http://localhost:8010"
  domain_from_request: false
  frontend_hmr: false

  # 日志
  log_level: "INFO"
  json_log: false

  # 数据目录
  base_data_dir: "/opt/application/ylabel/data"

  postgre_user: "ytlabel"
  postgre_password: "ldjk*dh2G#D7D*SD1s35djd"
  postgre_name: "label_studio"
  postgre_host: "10.130.121.112"
  postgre_port: 5432

  # redis
  redis_host: '10.130.18.74'
  redis_port: 6379
  redis_password: '123456'
  redis_db: 12

prod:
  # 基础设置
  debug: true
  allowed_hosts:
    - "*"
  secret_key: "7#33_!ae+t7eg1n#5c0+xa811^a5d!+a0=b8a!*ha04m9wve_("

  # 主机与前端
  host: "http://localhost:8080"
  frontend_hostname: "http://localhost:8010"
  domain_from_request: false
  frontend_hmr: false

  # 日志
  log_level: "INFO"
  json_log: false

  # 数据目录
  base_data_dir: "/opt/application/ylabel/data"

  postgre_user: "postgres"
  postgre_password: "postgres"
  postgre_name: "label_studio"
  postgre_host: "localhost"
  postgre_port: 5432

  # redis
  redis_host: '10.130.18.74'
  redis_port: 6374
  redis_password: '123456'
  redis_db: 12


